name = (input("Whats your name?: "))
age = (input("Whats your age?: "))
courseCd = (input("whats your course code?: "))
print ("Name: " + name )
print (type(name))
print ("Age: " + age )
print (type(age))
print ("Course Code: " + courseCd )
print (type(courseCd))
